### ISSUE TITLE
Demos and babylonjs-playground doesn't work on Edge browser

### ISSUE THREAD

**Issue by with4** [BabylonJS/Website#121]
When playground starts, following error message shows up.
Line 6:18795 - Object doesn't support property or method 'createQuery'
![image](https://user-images.githubusercontent.com/12877916/29652172-34a687ec-88df-11e7-9aa6-153bd7a210b8.png)

and Demos on website doesn't work on Edge like PBRGlossy, Sponza etc.. with white screen.
![image](https://user-images.githubusercontent.com/12877916/29652154-21a8f184-88df-11e7-8529-da09a1503dbb.png)

**Comment by deltakosh** [comment]
Thanks for pointing this out :) It will be fix in a couple of minutes :)
