### ISSUE TITLE
Suggestion: add exporters to download page

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Website#288]
If I'm a new user, I quickly want the tools to test the engine, but in the download page only stands the version builder (which is cool by the way).
Even if I'm a daily user, it allows me to quickly go to the repo so as to update my exporter(s).

IMO, have to clic to Documentation > Resources > find what's happens here and finally view the doc for each software exporter is not very convenient when discovering BJS.

Maybe a simple link to the github repo could be enough? Here just a simple proposal:

![download page proposal](https://i.imgur.com/pXjQHDq.png)

**Comment by deltakosh** [comment]
Like it a lot! Do you want to PR the change?

**Comment by Vinc3r** [comment]
I do it in 3 minutes on Photoshop, and I don't know scss :-p

**Comment by deltakosh** [comment]
It could be pure html:)

**Comment by Vinc3r** [comment]
It seems [pure html ](https://github.com/BabylonJS/Website/blob/master/versionBuilder/index.html)indeed :) So, 'will try a PR soon!

**Comment by deltakosh** [comment]
Thanks;)

**Comment by Vinc3r** [comment]
After rethinking, I don't think the "Use Editor" button have to be on this page, because if you download BJS, it's for use in custom project, so not with the online editor.

So I may remove this button. Is there another basics tools to add in side of "Exporters" button?
I also forgot to rename the "Generate" butotn into "Get you BabylonJS".

**Comment by deltakosh** [comment]
I would also rename the other button to "go to exporters repo"
