### ISSUE TITLE
suggestion: redirect https://models.babylonjs.com/ to "Available Meshes to Import" doc page

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Website#381]
it is a very tiny priority :-D but in case it's easy to do, https://models.babylonjs.com/ could be an easy link to remember when searching for an example mesh in a new playground

**Comment by deltakosh** [comment]
Good idea!! Need to update the DNS when I have a chance ;)

**Comment by RaananW** [comment]
models.babylonjs.com now redirects to the meshes directory in our assets' library. for example:

https://models.babylonjs.com/Rabbit.babylon

Notice that the DNS update might be in propagation so it might take a few minutes/hours until the update is available for everyone.
