### ISSUE TITLE
sandbox.babylonjs.com assetURL broken?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Website#394]
Windows 10 Enterprise
3ds Max 2018.4
Max2Babylon 1.3.32

When we use Export & Run in the exporter, it spawns the default browser (Chrome in our case) and attempts to load the sandbox with a local URL. But the file refuses to load, the sandbox remains in its default index.html state.
https://sandbox.babylonjs.com/?assetUrl=http://localhost:45478/Wood_ParquetStrip_1meter_1K_Bump.glb

When I try to drag-and-drop an exported GLB into the sandbox, Chrome downloads the file instead of loading it in BabylonJS.

Has something changed on your backend recently?

**Comment by deltakosh** [comment]
This should be back now (we were experiencing issues with our netlify isntance)
