### ISSUE TITLE
babylon.js.org

### ISSUE THREAD

**Issue by shinenelson** [BabylonJS/Website#398]
[js.org](js.org) has a [DNS service](https://dns.js.org) that provides [js.org](https://js.org) sub-domains that can point to websites hosted by providers like github, netlify, etc. I think we could move to babylon.js.org. It would look a lot more cooler :sunglasses: plus it could show our affiliation with the larger javascript community.

Since the [babylonjs.com](https://babylonjs.com) website is currently hosted on [netlify](https://bablyonjs.netlify.com), the only change that needs to be done from our part is to create a new pull request to the [js.org/dns.js.org](https://github.com/js.org/dns.js.org) repository with the new sub-domain.

I can create a pull request to [js-org/dns.js.org](https://github.com/js-org/dns.js.org) to assign the sub-domain to [babylon.js](https://github.com/BabylonJS/Website).

**Why would you want to change the existing domain?**
I think having a [js.org](js.org) sub-domain could show a better affiliation with the javascript community.
There are other services that use the [js.org](https://js.org) sub-domain as well. Some examples : 
* [browserless.js.org](https://browserless.js.org)
* [canvas.js.org](https://canvas.js.org)
* [cargo.js.org](https://cargo.js.org)
* [cnc.js.org](https://cnc.js.org)
* [csv.js.org](https://csv.js.org)
* [cycle.js.org](https://cycle.js.org)
* [impress.js.org](https://impress.js.org)
* [mobx.js.org](https://mobx.js.org)
* [redux.js.org](https://redux.js.org)
* [telegraf.js.org](https://telegraf.js.org)
* [webpack.js.org](https://webpack.js.org)

I'm asking approval / permission to do these :point_up_2: for [babylon.js](https://github.com/BabylonJS/Babylon.js).

**Comment by deltakosh** [comment]
Please go ahead :D And thanks a lot btw!

**Comment by shinenelson** [comment]
Since there are more than one sub-domain on the [source domain](https://babylonjs.com) and some redundant ones as well (in my personal opinion), I  thought I'd run the list by you first before I send this up for set up at [js-org/dns.js.org](https://github.com/js-org/dns.js.org). Please take a look at [this commit](https://github.com/shinenelson/dns.js.org/commit/1abc8891076a9757131c88f41ece7a42480985bb) for the full list that I've currently mapped and those that I'm going to send up for set up.

The sub-domains that I was able to find from the website and their mappings are as follows : 
* babylonjs.com (currently un-mapped) -> babylon.js.org => [babylonjs.netlify.com](babylonjs.netlify.com)
* [www.babylonjs.com](https://www.babylonjs.com) -> www.babylon.js.org => [babylonjs.netlify.com](https://babylonjs.netlify.com)
I would suggest to get rid of the www domain since we're already going to be a sub-domain. (we could keep it if you want it. I've included both in the list)
* [cdn.babylonjs.com](https://cdn.babylonjs.com) -> cdn.babylon.js.org => [babylonjs.github.io](https://babylonjs.github.io)
* [cyos.babylonjs.com](https://cyos.babylonjs.com) -> cyos.babylon.js.org => [cyos.netlify.com](https://cyos.netlify.com)
If you would rather prefer cyos.js.org, I've [committed](https://github.com/shinenelson/dns.js.org/commit/be2b6429f952ee4432f4dd5bc7412f8a0fc04a23) that too.
* [doc.babylonjs.com](https://doc.babylonjs.com) -> doc.babylon.js.org => [doc.netlify.com](https://doc.netlify.com)
* [forum.babylonjs.com](https://forum.babylonjs.com) -> forum.babylon.js.org => [babylonjs.hosted-by-discourse.com](https://babylonjs.hosted-by-discourse.com)
You'll probably have to change the settings for this on the Discourse instance directly for it to reflect the new sub-domain
* [models.babylonjs.com](https://models.babylonjs.com) -> models.babylon.js.org => [models.netlify.com](https://models.netlify.com)
This website is non-existent on netlify, even though the CNAME record still points to the website. I also found #381 to re-direct to the documentation page. So, do we need the sub-domain altogether?
* [playground.babylonjs.com](https://playground.babylonjs.com) -> playground.babylon.js.org => [playground.netlify.com](https://playground.netlify.com)
* [preview.babylonjs.com](https://preview.babylonjs.com) -> preview.babylon.js.org => [preview.netlify.com](https://preview.netlify.com)

Apart from the babylonjs.com sub-domains, I also [proposed](https://github.com/BabylonJS/SpectorJSWebsite/issues/9) moving [SpectorJS](https://github.com/BabylonJS/SpectorJSWebsite) to spector.js.org. I've [committed](https://github.com/shinenelson/dns.js.org/commit/3c91c00dab72677364353fd3536229d9216a30ff) that as well.

I'll proceed with the pull request after your review and approval.

**Comment by deltakosh** [comment]
Wait :) I thought you wanted the opposite ;) I won't change our domain DNS. 
I though you wanted to point from forum.babylon.js.org to forum.babylonjs.com and not the other way around
You should not point to netlify as we don't know where we will be in the future whereas the babylonjs.com will stay

**Comment by shinenelson** [comment]
That would defeat the purpose of the DNS service that [js.org](https://js.org) provides. I don't think reverse-mapping domains would be permitted by the service either. I would rather leave it as it is if you aren't interested in switching domains.

I thought I could convince you to switch over domains since that would show more better affiliation with the js community, being under the js.org umbrella, et al. like the other communities that I mentioned in my first post. It's your call to make.

> You should not point to netlify as we don't know where we will be in the future whereas the babylonjs.com will stay

Of course, you could always put in pull requests to [js-org/dns.js.org](https://github.com/js-org/dns.js.org) whenever you had to change. As long it is a static website hosted somewhere like [Github pages](https://pages.github.com), [Netlify](https://netlify.com), etc.

I'm closing this issue for now. If you feel like switching domains later, please re-open this issue. All I have to do is to send out the pull request. The changes have already been committed.

**Comment by deltakosh** [comment]
Don't get me wrong: I do appreciate your initiative a lot but I'm not convinced that having this indirection will help a lot
