### ISSUE TITLE
[suggestion] add a tutorial link on navigation bar

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Website#42]
As title say, it may be a cool thing to have direct link to [official tutorials](http://doc.babylonjs.com/tutorials) directly from main page ?

**Comment by deltakosh** [comment]
Feel free to PR:)

**Comment by Vinc3r** [comment]
OK, I will try to don't broke anything :)

**Comment by deltakosh** [comment]
No worry I'll check

**Comment by Vinc3r** [comment]
PR sent, it was just about adding a <a>, so I think nothing has broke
