### ISSUE TITLE
suggestion: main page featured demos should use content/community/config.json file

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/Website#471]
On the forum the demo makers are invited to update the [community/config.json](https://github.com/BabylonJS/Website/blob/master/src/content/community/config.json) file when showing their new projects, which is great. But this will not update the _[Featured demos](https://github.com/BabylonJS/Website/blob/master/src/content/config.json)_ of the main page of babylonjs.com.

Do you think it's possible that the Featured section automatically take the first 7 new demos from community/config.json?

Or maybe this Featured is a manual choice of particular demos, but who is in charge of this choice then?

**Comment by deltakosh** [comment]
Nope. featured are demos picked by us manually :)

But if you want to highlight some demos we can discuss it on the forum as well :)

**Comment by Vinc3r** [comment]
OK :) Note that the last time I have manually edit the featured json file to add the Bastille :-D

**Comment by deltakosh** [comment]
Yep and the demo is so beautiful that it deserved to be highlighted
