### ISSUE TITLE
Demo Carousel - Add 3D playground capability instead of video in home page

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Website#514]
The objective would be to replace the video carousel on the home page of www.babylonjs.com by actual 3D demos instead of videos. For this, the capability to be able to add Playground Code directly into the Home Page would need to be added with a way to switch demos.

![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/e4eeb2a5-b3af-4237-9684-58e7b28abd94)

**Comment by thomlucc** [comment]
The objective would be to replace the video carousel on the home page of www.babylonjs.com by actual 3D demos instead of videos.

![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/e4eeb2a5-b3af-4237-9684-58e7b28abd94)

**Comment by kevinbaconten** [comment]
Hello @thomlucc, I have a website too [bestgamesapk.com](https://bestgamesapk.com/dragon-city-mod-apk-cheat/) in which home page I have used a video carousel but want to add a 3D background. How this can possible?
thanks in advance,

**Comment by thomlucc** [comment]
Hi @kevinbaconten, The best place to discuss is on our forum: https://forum.babylonjs.com/ (you'll see that the community is very keen to help!). That said, as a first element of answer to your question, it depends what you want to do. Do you want the user to interact with the 3D background (like changing the point of view) or is it more a pre-recorded animation in 3D? Please make sure to give a little bit more details when you start the forum thread. Thanks!

**Comment by RaananW** [comment]
@PatrickRyanMS, @thomlucc - is this still needed?

**Comment by PatrickRyanMS** [comment]
We will be reworking the entire site for 6.0, so we will build this into the new template as we make it. Closing.
